server:
  port: 8080
spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    drop-first: true
  datasource:
      url: jdbc:postgresql://localhost:5432/library
      username: admin
      password: root
      driverClassName: org.postgresql.Driver